aropixel_admin:
    resource: '@AropixelAdminBundle/Resources/config/routes.yaml'
    prefix: /%admin_path%

# Public download route (must be outside of protected prefix)
aropixel_admin_download:
    resource: '@AropixelAdminBundle/Resources/config/routes/download.yaml'

aropixel_blog:
    resource: '@AropixelBlogBundle/Resources/config/routes.yaml'
    prefix: /%admin_path%

aropixel_page:
    resource: '@AropixelPageBundle/Resources/config/routes.yaml'
    prefix: /%admin_path%
