aropixel_admin:
    client:
        name: "Indie Label"
        link: "https://www.indie-label-shop.local/"
        email: "mail@post.aropixel.com"
    copyright:
        name: "Aropixel"
        link: "https://www.aropixel.com/"
    translations:
        locales: ['fr', 'en']
