doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false
        resolve_target_entities:
            Sylius\Component\Core\Model\AddressInterface: App\Entity\Address
            Sylius\Component\Core\Model\ChannelInterface: App\Entity\Channel
            Sylius\Component\Core\Model\CustomerInterface: App\Entity\Customer
            Sylius\Component\Core\Model\OrderInterface: App\Entity\Order
            Sylius\Component\Core\Model\OrderItemInterface: App\Entity\OrderItem
            Sylius\Component\Core\Model\OrderItemUnitInterface: App\Entity\OrderItemUnit
            Sylius\Component\Inventory\Model\InventoryUnitInterface: App\Entity\OrderItemUnit
            Sylius\Component\Core\Model\PaymentInterface: App\Entity\Payment
            Sylius\Component\Core\Model\PaymentMethodInterface: App\Entity\PaymentMethod
            Sylius\Component\Core\Model\ProductInterface: App\Entity\Product
            Sylius\Component\Product\Model\ProductInterface: App\Entity\Product
            Sylius\Component\Product\Model\ProductTranslationInterface: App\Entity\ProductTranslation
            Sylius\Component\Product\Model\ProductVariantInterface: App\Entity\ProductVariant
            Sylius\Component\Core\Model\ProductVariantInterface: App\Entity\ProductVariant
            Sylius\Component\Core\Model\PromotionInterface: App\Entity\Promotion
            Sylius\Component\Core\Model\ShipmentInterface: App\Entity\Shipment
            Sylius\Component\Core\Model\ShippingMethodInterface: App\Entity\ShippingMethod
            Sylius\Component\Addressing\Model\CountryInterface: App\Entity\Country
            Sylius\Component\Addressing\Model\ProvinceInterface: App\Entity\Province
            Sylius\Component\Addressing\Model\ZoneInterface: App\Entity\Zone
            Sylius\Component\Taxation\Model\TaxCategoryInterface: App\Entity\TaxCategory
            Sylius\Component\Core\Model\TaxRateInterface: App\Entity\TaxRate
            Sylius\Component\Addressing\Model\ZoneMemberInterface: App\Entity\ZoneMember
            Sylius\Component\Product\Model\ProductOptionInterface: App\Entity\ProductOption
            Sylius\Component\Product\Model\ProductOptionTranslationInterface: App\Entity\ProductOptionTranslation
            Sylius\Component\Product\Model\ProductOptionValueInterface: App\Entity\ProductOptionValue
            Sylius\Component\Product\Model\ProductOptionValueTranslationInterface: App\Entity\ProductOptionValueTranslation

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
