# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin_path: '%env(ADMIN_PATH)%'
    app.locales: "%env(csv:APP_LOCALES)%"
    app.default_locale: 'fr'
    app.cart.expiration_days: 14

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Component\Track\MessageHandler\EncodeTrackMp3Handler:
        arguments:
            $previewsStorage: '@previews.storage'
            $privateStorage: '@private.storage'

    App\Component\Download\MessageHandler\GenerateDownloadHandler:
        arguments:
            $privateStorage: '@private.storage'

    App\Controller\Front\DownloadController:
        arguments:
            $privateStorage: '@private.storage'
            $kernelEnvironment: '%kernel.environment%'

    App\Component\Download\DownloadTokenManager:
        arguments:
            $kernelEnvironment: '%kernel.environment%'

    App\Component\Mail\MessageHandler\SendOrderConfirmedHandler:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'

    App\Component\Mail\MessageHandler\SendDownloadReadyHandler:
        arguments:
            $mailerFrom: '%env(MAILER_FROM)%'

    App\Routing\FrontRouteLoader:
        arguments:
            $locales: '%app.locales%'
        tags:
            - { name: routing.loader }

    App\EventListener\LocaleSubscriber:
        arguments:
            $locales: '%app.locales%'

    App\Security\LoginFormAuthenticator:
        arguments:
            $locales: '%app.locales%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@prod:
    services:
        App\Component\Download\DownloadTokenManager:
            arguments:
                $kernelEnvironment: 'prod'
                $s3Client: '@cellar_spaces_service'
                $cellarBucket: '%env(CELLAR_BUCKET)%'
                $privateStoragePrefix: 'private'
